#!/bin/bash

staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cpp|h)$')
for staged_file in $staged_files; do
  # If the file is not formatted according to the Google style guide, format it
  if ! git cat-file -p :./$staged_file | clang-format --style="Google" --dry-run --Werror --sort-includes --assume-filename=$staged_file >/dev/null 2>&1; then
    clang-format --style="Google" --sort-includes -i $staged_file
    formatter_ran=true
    echo "Clang-format: $staged_file was formatted."
  fi
done

# If the formatter ran, fail the commit, so the user can add the changes to the commit
if [ "$formatter_ran" = true ]; then
  echo "Error: Clang-format: Some files were formatted. Please add them to your commit."
  exit 1
fi
